-- ユーザーテーブルの作成
CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER', -- 'USER', 'BREWERY', 'ADMIN'
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', -- 酒蔵の承認状態など ('PENDING', 'ACTIVE', etc.)
    is_deleted TINYINT(1) NOT NULL DEFAULT 0, -- BAN・論理削除フラグ
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);